version: '3.8'

services:
    back_end:
        image: psppx/team-14-backend:${BACK_END_VERSION}
        build:
            context: ./back-end
            target: production
            dockerfile: ./Dockerfile
    front_end:
        image: psppx/team-14-frontend:${FRONT_END_VERSION}
        build:
            context: ./front-end
            target: production
            dockerfile: ./Dockerfile