version: '3.8'

services:
    back_end:
        build:
            context: ./back-end
            target: development
            dockerfile: ./Dockerfile
        command: yarn run start:dev
        ports:
            - 8080:3000
        volumes:
            - ./back-end:/usr/src/app
        restart: unless-stopped
    front_end:
        build:
            context: ./front-end
            target: production
            dockerfile: ./Dockerfile
        ports:
            - 3000:80