version: '3.8'

services:
    dev:
        build:
            context: ./back-end
            target: development
            dockerfile: ./Dockerfile
        command: yarn run start:dev
        ports:
            - 8080:80
        volumes:
            - ./back-end:/usr/src/app
        restart: unless-stopped
    prod:
        build:
            context: ./back-end
            target: production
            dockerfile: ./Dockerfile
        command: yarn run start:prod
        ports:
            - 8080:80
        restart: unless-stopped